#!/bin/bash
#
# lsinitramfs - dump the contents of an initramfs image
#
# Copyright (C) 2011 by Dave Reisner <d@falconindy.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

die() {
  local mesg=$1; shift
  printf "error: $fmt\n" "$@"
  exit 1
}

usage() {
  cat<<USAGE
usage: ${0##*/} [options] <initramfs>

  Options:
   -h             display this help
   -v             more verbose output
   -x             extract image to disk

USAGE
  exit 1
}

declare verbose=
declare list='--list'

while getopts ':hvx' flag; do
  case $flag in
    h) usage ;;
    v) verbose='--verbose'  ;;
    x) unset list ;;
    \?) die "invalid option -- '$OPTARG'" ;;
  esac
done
shift $(( OPTIND - 1 ))

declare image=$1

[[ $image ]] || usage
[[ -f $image ]] || die "$image: No such file"

bsdcpio -i --quiet $verbose $list <"$image"

