=head1 NAME

geninit - modular initramfs creation utility

=head1 SYNOPSIS

Usage: I<geninit> [ options ]

=head1 DESCRIPTION

geninit is a tool for creating cpio archives to be used as an initial ramfs
during system bootstrap. It features a modular design, making it easy to
tailor the image to the system's hardware and software needs.

=head1 OPTIONS

=over 4

=item B<-b>

Specify a base directory other than /. This is reserved for usage during a
chroot. geninit will attempt to use as much as possible from the guest system,
drawing only from the host system when necessary.

=item B<-c> I<FILE>

Use an alterate config file. Defaults to I</etc/geninit.conf>.

=item B<-g> I<PATH>

Specify the absolute path of the generated initramfs image. If unspecified,
a dry-run will be performed and no image will be created.

=item B<-H> I<BUILDER>

Display the help message for a I<builder>. A list of available builders can
be generated with the B<-L> option.

=item B<-h>

Display the help message and quit.

=item B<-k> I<KERNEL>

Specify an alternate kernel version to create an image for. The kernel can be
specified as an exact version, or provided as a path to the kernel bzImage
itself. By default, this is the currently loaded kernel.

=item B<-L>

List all available builders for use in the I<builders> array in the config
file.

=item B<-p> I<PRESET>

Specify a preset file to drive image creation. This is any file named with a
.preset extension in I</etc/geninit.d>. An example preset file is packaged
with geninit for explanatory purpose.

=item B<-S> I<BUILDERS>

A comma delimited list of builders to skip during image creation.

=item B<-s>

Instruct geninit to avoid removal of the temporary workspace after image
creation. This is useful for debugging purposes.

=item B<-t> I<PATH>

Specify an alterate version to the temporary directory used as a workspace. This
needs to be a writeable directory with a minimum of 20mb free.

=item B<-z> I<COMPRESSION>

Override the compression method specified by the config file. geninit supports
compression via B<gzip>, B<bzip2>, B<lzma>, and B<xz>. You can also use B<none>
to disable compression entirely. Please note that your kernel I<must> support
your method and choice and your kernel will not be checked for this support! If
in doubt, gzip is a safe choice.

=back

=head1 AUTHOR

Dave Reisner E<lt>d@falconindy.comE<gt>

