#!/bin/sh

. /libinit

if [ -e /consolefont.psfu ]; then
  font=/consolefont.psfu
elif [ -e /consolefont.psf ]; then
  font=/consolefont.psf
else
  err "No consolefont found."
  exit 1
fi

msg '%s\n' "Loading console font..."
/usr/sbin/setfont -C /dev/console $font
