#!/bin/sh

/sbin/modprobe -q dm-mod 2>/dev/null

if [ -e /sys/class/misc/device-mapper ]; then
  if [ ! -e /dev/mapper/control ]; then
    IFS=':' read major minor </sys/class/misc/device-mapper/dev
    /bin/mknod /dev/mapper/control c "$major" "$minor"
  fi

  echo ":: Activating logical volumes..."
  [ -d /etc/lvm ] && /sbin/lvm vgscan
  /sbin/lvm ${quiet:+--quiet} vgchange --sysinit -ay
fi

