#!/bin/sh

. /libinit

if [ -z "$resume" ]; then
  err "no device specified for resume!"
  exit 1
fi

# might be @(swap|file):/dev/sdxy
resumedev=${resume#*:}

if poll_device "$resumedev" "$rootdelay"; then
  if [ "$resume" != "${resume/:}" ]; then
    # tuxonice
    tuxoniceroot='/sys/power/tuxonice'
    if [ -d "$tuxoniceroot" ]; then
      echo "$resume" > "$tuxoniceroot/resume"
      echo > "$tuxoniceroot/do_resume"
    fi
  else
    # vanilla
    if [ -e "/sys/power/resume" ]; then
      printf "%d:%d" $(stat -Lc "0x%t 0x%T" "$resume") > /sys/power/resume
    fi
  fi
fi

