#!/bin/bash

build() {
  add_driver_classes drivers/ata drivers/block

  if (( ! $? )); then
    add_module sd_mod
  fi
}

helpmsg() {
  cat<<EOF
  This hook loads the necessary modules for an ata root device. It covers PATA
  as well as SATA.
EOF
}
