#!/bin/bash

build() {
  add_driver_classes drivers/ata drivers/block && add_module sd_mod
}

helpmsg() {
  cat<<HELPEOF
  This provides the necessary modules for a PATA or SATA root device
HELPEOF
}

# vim: set et ts=2 sw=2:
