#!/bin/bash

build() {
  if [[ ! -d /sys/devices ]]; then
    err "/sys does not appear to be mounted. Unable to use autodetection"
    return 1
  fi

  # generate a list of modules from aliases in /sys/devices
  find /sys/devices/ -name modalias -exec sort -u {} + |\
    xargs -I {} modprobe -d "${basedir:-/}" --set-version "$kernver" --resolve-alias {} |\
    sort -u >>"$autodetect_cache"

  if (( UID == 0 )) || [[ $(groups) == *disk* ]]; then
    if ! findmnt -uno fstype / >>"$autodetect_cache"; then
      err "failed to detect root filesystem"
    fi

    if [[ -x /sbin/mdadm ]]; then
      /sbin/mdadm -Esv /dev/hd* /dev/sd* /dev/rd/* /dev/ida/* /dev/cciss/* /dev/ataraid/* /dev/mapper/* |\
        sed -n 's/.*level=\([^ ]\+\) .*/\1/p' |\
        sed 's/\<raid[456]\>/raid456/g' | sort -u >>"$autodetect_cache"
    fi
  else
    err "User does not have proper permissions to read superblocks, raid and filesystem modules are not detected"
  fi

}

helpmsg() {
  cat<<HELPEOF
  This hook autodetects needed modules for the initramfs. This hook should be
  placed after base in order to best take advantage of it. Any hooks placed
  prior to this hook will be installed in full.
HELPEOF
}

# vim: set et ts=2 sw=2:
