#!/bin/bash

build() {
  local mod

  add_dir /proc
  add_dir /sys
  add_dir /dev

  add_dir /bin
  add_dir /sbin

  add_dir /lib
  add_dir /lib/modules

  add_dir /usr
  add_dir /usr/bin
  add_dir /usr/lib
  add_dir /usr/sbin

  add_device /dev/null c 1 3
  add_device /dev/zero c 1 5
  add_device /dev/console c 5 1
  add_device /dev/mem c 1 1

  add_binary /bin/busybox
  add_binary /sbin/modprobe
  add_binary /sbin/blkid

  add_binary "${_sharedir}/init" "/init"

  # write a tasty config file that our init will enjoy
  {
    printf '%s %d' '%MODULES%' "${#modules[*]}"
    printf ' %s' "${modules[@]}"
    printf '\n'

    printf '%s' '%HOOKS%'
    printf ' %s' "${builders[@]}"
    printf '\n'
  } > "$tmpdir/config"

  add_file "$tmpdir/config" "/config"

  add_file /etc/modprobe.d/usb-load-ehci-first.conf
}

helpmsg() {
  cat<<EOF
  This hook provides a crucial base layout for the initramfs. Do not remove
  skip this unless you know exactly what you are doing.
EOF
}
