#!/bin/bash

build() {
  # necessary mount points
  add_dir /new_root
  add_dir /proc
  add_dir /sys
  add_dir /dev
  add_dir /run

  # busybox --install won't create dirs
  add_dir /usr/bin
  add_dir /usr/sbin
  add_dir /sbin
  add_dir /bin

  add_binary "@$_sharedir/init" "/init"
  add_binary /lib/initcpio/busybox /bin/busybox
  add_binary /sbin/modprobe
  add_binary /sbin/blkid

  # we need this for hooks to run
  add_symlink /bin/busybox /bin/sh

  add_file /etc/modprobe.d/usb-load-ehci-first.conf
}

helpmsg() {
  cat<<HELPEOF
  This hook provides a crucial base layout for the initramfs. Do not remove
  skip this unless you know exactly what you are doing.
HELPEOF
}

# vim: set et ts=2 sw=2:
