#!/bin/bash

build() {
  use_hookscript
  add_module btrfs
  add_binary /sbin/btrfs
}

helpmsg() {
  cat<<HELPEOF
  This builder supports multi device btrfs volumes.
HELPEOF
}

# vim: set et ts=2 sw=2:
