#!/bin/bash

build() {
  use_hookscript
  eval "$(grep "^CONSOLEFONT=" /etc/rc.conf)"

  if [[ -z $CONSOLEFONT ]]; then
    err "no appropriate file found for consolefont"
    return 0
  fi

  if [ -e /usr/share/kbd/consolefonts/$CONSOLEFONT.psfu.gz ]; then
    CONSOLEFONT_FILE_GZ="/usr/share/kbd/consolefonts/$CONSOLEFONT.psfu.gz"
    CONSOLEFONT_FILE="$(mktemp ${TMPDIR}/consolefont.psfu.XXXXXX)"
    zcat ${CONSOLEFONT_FILE_GZ} > ${CONSOLEFONT_FILE}
    add_file ${CONSOLEFONT_FILE} /consolefont.psfu
  elif [ -e /usr/share/kbd/consolefonts/$CONSOLEFONT.psf.gz ]; then
    CONSOLEFONT_FILE_GZ="/usr/share/kbd/consolefonts/$CONSOLEFONT.psf.gz"
    CONSOLEFONT_FILE="$(mktemp ${TMPDIR}/consolefont.psf.XXXXXX)"
    zcat ${CONSOLEFONT_FILE_GZ} > ${CONSOLEFONT_FILE}
    add_file ${CONSOLEFONT_FILE} /consolefont.psf
  else
    echo "consolefont: Font file does not exist or does not end with .psf.gz or .psfu.gz."
  fi
}

helpmsg() {
  cat<<EOF
  This hook loads consolefont specified in rc.conf during early userspace.
EOF
}
