#!/bin/bash

build() {
  use_hookscript
}

helpmsg() {
  cat<<HELPEOF
  This hook lowers the console log level to 3. It is useful when the user has
  to interact with the boot process during early userspace (like when entering
  a passphrase).
HELPEOF
}

# vim: set et ts=2 sw=2:
