#!/bin/bash

build() {
  add_file "/lib/initcpio/custom.dsdt" "/DSDT.aml"
}

helpmsg() {
  cat<<HELPEOF
  This hook loads a custom acpi dsdt file during boot. Place your custom dsdt
  file for inclusion in: /usr/share/geninit/custom.dsdt
HELPEOF
}

# vim: set et ts=2 sw=2:
