#!/bin/bash

build() {
  add_module dm-crypt
  add_all_modules crypto drivers/crypto

  use_hookscript

  add_binary "/sbin/cryptsetup"
  add_binary "/sbin/dmsetup"

  add_file "/lib/udev/rules.d/10-dm.rules"
  add_file "/lib/udev/rules.d/13-dm-disk.rules"
  add_file "/lib/udev/rules.d/95-dm-notify.rules"
}

helpmsg() {
  cat<<HELPEOF
  This builder allows for an encrypted root device. Refer to the wiki for a
  detailed reference on setting up encryption:
    https://wiki.archlinux.org/index.php/LUKS
HELPEOF
}

# vim: set et ts=2 sw=2:
