#!/bin/bash

build() {
  add_checked_modules drivers/ide && add_module ide-gd_mod
}

helpmsg() {
  cat<<HELPEOF
  This builder loads the necessary modules for a legacy ide root device. Chances
  are high that you can use the ata hook instead of this.
HELPEOF
}

# vim: set et ts=2 sw=2:
