#!/bin/bash

build() {
  add_driver_classes drivers/ide
  if (( ! $? )); then
    add_module ide-gd_mod
  fi
}

helpmsg() {
  cat<<EOF
  This hook loads the necessary modules for a legacy ide root device. Chances
  are high that you can use the ata hook instead of this.
EOF
}
