#!/bin/bash

build() {
  use_hookscript

  eval "$(grep -E "^(LOCALE|KEYMAP)=" /etc/rc.conf)"
  if [[ $KEYMAP ]]; then
    KEYMAP_FILE="$(mktemp ${TMPDIR}/keymap.XXXXXX)"
    UTF8_FILE="$(mktemp ${TMPDIR}/keymap.XXXXXX)"
    if [[ $LOCALE =~ utf ]]; then
      echo "UTF8='yes'" > $UTF8_FILE
      /bin/loadkeys -q -u $KEYMAP -b > $KEYMAP_FILE
    else
      echo "UTF8='no'" > $UTF8_FILE
      /bin/loadkeys -q $KEYMAP -b > $KEYMAP_FILE
    fi
    add_file "@$KEYMAP_FILE" /keymap.bin
    add_file "@$UTF8_FILE" /keymap.utf8
  fi
}

helpmsg() {
  cat<<EOF
  This hook loads keymap(s) specified in rc.conf during early userspace.
EOF
}
