#!/bin/bash

build() {
  use_hookscript

  add_module dm-mod
  add_module dm-snapshot
  add_module dm-mirror

  add_binary "/sbin/lvm"
  add_binary "/sbin/dmsetup"

  add_file "/lib/udev/rules.d/10-dm.rules"
  add_file "/lib/udev/rules.d/13-dm-disk.rules"
  add_file "/lib/udev/rules.d/95-dm-notify.rules"
  add_file "/lib/udev/rules.d/11-dm-lvm.rules"
  add_file "/lib/initcpio/udev/11-dm-initramfs.rules" "/lib/udev/rules.d/11-dm-initramfs.rules"
}

helpmsg() {
  cat<<HELPEOF
  This builder loads the necessary modules for an lvm2 root device.
HELPEOF
}

# vim: set et ts=2 sw=2:
