#!/bin/bash

build() {
  use_hookscript

  add_module phram
  add_module mtdblock

  add_binary /usr/bin/memdiskfind

  add_file /lib/initcpio/udev/01-memdisk.rules /lib/udev/rules.d/01-memdisk.rules
}

helpmsg() {
  cat<<HELPEOF
  This builder detects a virtual disk created by the memdisk tool
  (http://syslinux.zytor.com/wiki/index.php/MEMDISK).
HELPEOF
}

# vim: set et ts=2 sw=2:
