#!/bin/bash

build() {
  add_checked_modules drivers/pcmcia drivers/ide/legacy && add_module sd_mod

  add_binary "/lib/udev/pcmcia-socket-startup"
  add_binary "/lib/udev/pcmcia-check-broken-cis"
  add_file "/lib/udev/rules.d/60-pcmcia.rules"
  add_file "/etc/pcmcia/config.opts"
}

helpmsg() {
  cat<<HELPEOF
  This builder provides the necessary modules for a pcmcia root device.
HELPEOF
}

# vim: set et ts=2 sw=2:
