#!/bin/bash

build() {
  add_driver_classes drivers/scsi drivers/block drivers/message/fusion
  if (( ! $? )); then
    add_module sd_mod
  fi
}

helpmsg() {
  cat<<EOF
  This hook loads the necessary modules for an scsi root device.
EOF
}
