#!/bin/bash

build() {
  modulefilter=('*_cs')
  add_driver_classes drivers/scsi drivers/block drivers/message/fusion &&
    add_module sd_mod
}

helpmsg() {
  cat<<EOF
  This hook loads the necessary modules for an scsi root device.
EOF
}
