#!/bin/bash

build() {
  MODFILTER=('*_cs')
  add_checked_modules drivers/scsi drivers/block drivers/message/fusion &&
    add_module sd_mod
}

helpmsg() {
  cat<<HELPEOF
  This builder loads the necessary modules for an scsi root device.
HELPEOF
}

# vim: set et ts=2 sw=2:
