#!/bin/bash

build() {
  # user config
  add_file /etc/udev/udev.conf

  add_binary /sbin/udevd
  add_binary /sbin/udevadm

  # udev tools
  for tool in firmware {ata,path,scsi,usb}_id; do
    add_file "/lib/udev/$tool"
  done

  # default rules
  for rules in {50-{firmware,udev-default},60-persistent-storage,80-drivers}.rules; do
    add_file "/lib/udev/rules.d/$rules"
  done
}

helpmsg() {
  cat<<HELPEOF
  This builder provides udev to detect and load the modules for your root device.
  It is required for loading firmware. This builder is recommended.
HELPEOF
}

# vim: set et ts=2 sw=2:
