#!/bin/bash

build() {
  add_driver_classes drivers/usb/host
  if (( ! $? )); then
    add_module usb_storage
    add_module sd_mod
    add_module sr_mod
    add_driver_classes drivers/usb/storage
  fi
}

helpmsg() {
  cat<<EOF
  This hook loads the necessary modules for an usb root device.
EOF
}
