#!/bin/bash

build() {
  add_checked_modules drivers/usb/{host,storage} && add_module sd_mod
}

helpmsg() {
  cat<<HELPEOF
  This builder loads the necessary modules for an usb root device.
HELPEOF
}

# vim: set et ts=2 sw=2:
