#!/bin/bash

build() {
  if add_checked_modules drivers/usb/host; then
    add_module usb_storage
    add_module sd_mod
    add_module sr_mod
    add_checked_modules drivers/usb/storage
  fi
}

helpmsg() {
  cat<<HELPEOF
  This hook loads the necessary modules for an usb root device.
HELPEOF
}

# vim: set et ts=2 sw=2:
