#!/bin/bash

build() {
  add_checked_modules drivers/usb/host drivers/hid/usbhid
}

helpmsg() {
  cat<<HELPEOF
  This builder loads the necessary modules for an usb input device.
HELPEOF
}

# vim: set et ts=2 sw=2:
