#!/bin/bash

build() {
  add_module uvesafb

  add_binary "/sbin/v86d"
  add_file "/etc/modprobe.d/uvesafb.conf"
}

helpmsg() {
  cat<<HELPEOF
This builder includes support for v86d, the userspace helper for uvesafb.
HELPEOF
}

# vim: set et ts=2 sw=2:
